version: '3.7'
services:
  php:
    container_name: php-fpm
    build:
      context: ./php-fpm
    ports:
      - "${PHP_PORT}:9001"
    volumes:
      - ./../:/opt/supersaas:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./../:/opt/supersaas:cached
